language: node_js
node_js:
  - "12"
services:
  - docker

before_install:
 - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t fzhange/docker-ci:latest
  - docker push fzhange/docker-ci:latest