language: node_js
node_js:
  - "8.9.4"
services:
  - docker

before_install:
 - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t fzhange/docker-ci:latest .
  - docker push fzhange/docker-ci:latest